# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad053b6fbe645002d847d3a396488247f6ffff62b3e4aeac1f36976c1415d350d439b24421eac299db1ce888fc1cfbff6b15da341d06f1c334b8f75366475553

test:
  secret_key_base: a8094c0e40d65931c6a2022bc12187710575a274217ffe0cfefe798c27d9b14e5c0fa92bc266b5eac1bdb125ac321295956c5279abad20570467bd388309d73c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
